import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import TanstackQueryProvider from "@/providers/TanstackQueryProvider";

export const metadata: Metadata = {
  title: "피파전적검색",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <TanstackQueryProvider>
          <Header />
          {children}
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
